"""
Pydantic schemas for API request validation and response serialization.
"""

from datetime import date
from typing import Any
from pydantic import BaseModel, Field, field_validator


# ── Request ──────────────────────────────────────────────────────────────────

class AnalysisRequest(BaseModel):
    """
    Query parameters / form fields that accompany the uploaded Excel file.
    Dates are accepted as ISO-8601 strings (YYYY-MM-DD) and coerced to date objects.
    """
    start_date: date = Field(..., description="Analysis start date (YYYY-MM-DD)")
    end_date: date = Field(..., description="Analysis end date (YYYY-MM-DD)")

    @field_validator("end_date")
    @classmethod
    def end_must_be_after_start(cls, end: date, info) -> date:
        start = info.data.get("start_date")
        if start and end < start:
            raise ValueError("end_date must be on or after start_date.")
        return end


# ── Response ─────────────────────────────────────────────────────────────────

class WeeklyStatRecord(BaseModel):
    """Raw aggregated statistics for a single weekly bucket."""
    week_ending: str = Field(..., description="ISO date of the Sunday ending the week")
    metrics: dict[str, Any] = Field(
        ..., description="Column-level aggregates (sum / mean) for the week"
    )


class ThemeGroupRecord(BaseModel):
    """Grouped description entries that belong to the same work theme."""
    theme: str
    count: int
    entries: list[str] = Field(
        default_factory=list,
        description="Description rows that were grouped under this theme",
    )


class WeeklySummarySectionRecord(BaseModel):
    """Single part of the executive weekly summary."""
    title: str
    text: str


class WeeklySummaryRecord(BaseModel):
    """AI-generated narrative paired with its raw stats."""
    week_ending: str
    stats: WeeklyStatRecord
    description_entries: list[str] = Field(
        default_factory=list,
        description="Raw description rows from the workbook for the week",
    )
    theme_groups: list[ThemeGroupRecord] = Field(
        default_factory=list,
        description="Description rows grouped into work themes",
    )
    week_summary: str = Field(
        ..., description="Short executive summary of the whole week"
    )
    week_summary_sections: list[WeeklySummarySectionRecord] = Field(
        default_factory=list,
        description="Three-part executive summary sections",
    )
    ai_summary: str = Field(
        ..., description="Narrative generated by the AI model"
    )
    summary_points: list[str] = Field(
        default_factory=list,
        description="Bullet-point highlights for the week",
    )
    peak_day: str | None = Field(
        None, description="Date identified as the peak-performance day"
    )
    trend_vs_previous_week: str | None = Field(
        None, description="Brief trend comparison to the preceding week"
    )


class AnalysisResponse(BaseModel):
    """Top-level response returned by /analyze."""
    status: str = "success"
    file_name: str
    start_date: str
    end_date: str
    total_weeks_analyzed: int
    weekly_results: list[WeeklySummaryRecord]


class ErrorResponse(BaseModel):
    """Structured error payload."""
    status: str = "error"
    error_type: str
    message: str
    detail: str | None = None
